### ISSUE TITLE
Index Error After Adding API Keys

### ISSUE THREAD

**Issue by wery67564** [superhedgy/AttackSurfaceMapper#11]
Had it running, then added all api keys besides linkedin and weleakinf_priv and it is now throwing this error:

![Screenshot from 2019-08-10 16-34-45](https://user-images.githubusercontent.com/22899183/62826631-c9627800-bb8c-11e9-877b-30932d9e9780.png)

**Comment by ojensen5115** [comment]
Based on the code, I would assume you have messed up your `keylist.asm` somehow. That error is telling you that you have a line in your keylist that does not contain three space-separated tokens. Double check that the equals signs have spaces around them (`virustotal = "xxxx"`, not `virustotal="xxxx"), and that you don't have a spurious newline anywhere.

**Comment by wery67564** [comment]
There was a spurious newline, works a charm now.
