### ISSUE TITLE
selenium missing from requirements

### ISSUE THREAD

**Issue by cFire** [superhedgy/AttackSurfaceMapper#2]
selenium is required, but not listed in `requirements.txt`

**Comment by superhedgy** [comment]
Thanks again, I will add it in the requirements file.

**Comment by Oj18** [comment]
It's still not there?

**Comment by DFW1N** [comment]
OJ18 run these if you are using linux 
use sudo apt-get install python3-pip to install pip for python3
use sudo python3 -m pip install -U selenium to install selenium for python3
Hopefully fixes it for you

**Comment by DFW1N** [comment]
> 
> 
> It's still not there?

OJ18 run these if you are using linux
use sudo apt-get install python3-pip to install pip for python3
use sudo python3 -m pip install -U selenium to install selenium for python3
Hopefully fixes it for you

**Comment by Oj18** [comment]
Yeah already installed it with Pip when it gave me the ImportError. Just want to make sure at some point it gets added to the requirements(.txt) for newer / inexperienced users.
