### ISSUE TITLE
NameError: name 'colorama' is not defined

### ISSUE THREAD

**Issue by mrtass** [superhedgy/AttackSurfaceMapper#21]
Hi
followed installation instruction as well as requirements.txt 
im getting this error during scan 
Any suggestions ?
Thanks

```
Traceback (most recent call last):
  File "/home/tass/Desktop/AttackSurfaceMapper/modules/buckethunter.py", line 43, in passive_query
    if gwf_api["buckets_count"] > 0:
KeyError: 'buckets_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ASM.py", line 890, in <module>
    main(keychain,sw1,output_path,c1)
  File "ASM.py", line 666, in main
    buckethunter.passive_query(target_list[key],keychain["grayhatwarfare"])# Passive
  File "/home/tass/Desktop/AttackSurfaceMapper/modules/buckethunter.py", line 52, in passive_query
    cprint ("error","[*] Error: connecting with GrayHatWarfare API",1)
  File "/home/tass/Desktop/AttackSurfaceMapper/modules/buckethunter.py", line 14, in cprint
    colorama.init()
NameError: name 'colorama' is not defined
```

**Comment by rascyber** [comment]
Add the two lines below to the import section of buckethunter.py and it works.

import colorama
from colorama import Fore, Style

**Comment by mrtass** [comment]
thanks for suggestion, however the issue was with missing grayhatwarfare API.
once configure the scan went fine

**Comment by rascyber** [comment]
> thanks for suggestion, however the issue was with missing grayhatwarfare API.
> once configure the scan went fine

I am still getting that error "Error: connecting with GrayHatWarfare API" 

What is the fix to configure the API?

**Comment by mrtass** [comment]
goto https://buckets.grayhatwarfare.com/
regisdter an account and get the API key.
place the API key in the keylist.asm
