### ISSUE TITLE
Error message in Windows only

### ISSUE THREAD

**Issue by tsai0009** [superhedgy/AttackSurfaceMapper#22]
I've tried ASM directly in Windows 10, in a Windows 10 VM and in CentOS VM.

Both Windows have given me this error:

![image](https://user-images.githubusercontent.com/43188094/63187424-dc61c600-c02c-11e9-89e1-6e93667336f2.png)

The command is just the standard command:
python ASM.py -t DSM.com -ln -o demo_run -w resources/top100_sublist.txt

And yes it should be using python 3.7.3 as I typed python --version and got that.

**Comment by superhedgy** [comment]
It seems Python is the issue here, it was optimised to run on Mac OS. I will have to test it out against Windows.

**Comment by jieyunhu** [comment]
I had the same proplem,just commented out a piece of code to make it works.
From the screenshot we can see that in the windows,the original code would have imported the threading module and assigned its threat object to multiprocessing.Process,but the threat object  has no attribute 'pid' or 'end'.

![subbrute](https://user-images.githubusercontent.com/45312034/64157980-44f0d580-ce6a-11e9-8b3e-27a843bb6c9c.png)

**Comment by tsai0009** [comment]
This is what I eventually did as well. It works like this.
