### ISSUE TITLE
Error message in Elementry OS

### ISSUE THREAD

**Issue by Sipho68** [superhedgy/AttackSurfaceMapper#23]
Traceback (most recent call last):
  File "/home/siphon/AttackSurfaceMapper/modules/buckethunter.py", line 43, in passive_query
    if gwf_api["buckets_count"] > 0:
KeyError: 'buckets_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ASM.py", line 890, in <module>
    main(keychain,sw1,output_path,c1)
  File "ASM.py", line 666, in main
    buckethunter.passive_query(target_list[key],keychain["grayhatwarfare"])# Passive
  File "/home/siphon/AttackSurfaceMapper/modules/buckethunter.py", line 52, in passive_query
    cprint ("error","[*] Error: connecting with GrayHatWarfare API",1)
  File "/home/siphon/AttackSurfaceMapper/modules/buckethunter.py", line 14, in cprint
    colorama.init()
NameError: name 'colorama' is not defined

**Comment by anil3a** [comment]
I have same error in my Windows 10 Sub System of Ubuntu 18.04.2

**Comment by anil3a** [comment]
@Sipho68 I have fixed my issue by importing these two modules in your
`/home/siphon/AttackSurfaceMapper/modules/buckethunter.py` line 43

```
   import colorama
   from colorama import Fore, Style
```

Hope this helps. Cheers

**Comment by Sipho68** [comment]
> @Sipho68 I have fixed my issue by importing these two modules in your
> `/home/siphon/AttackSurfaceMapper/modules/buckethunter.py` line 43
> 
> ```
>    import colorama
>    from colorama import Fore, Style
> ```
> 
> Hope this helps. Cheers

Did help, thanks Anil3a

**Comment by ZachR0** [comment]
> @Sipho68 I have fixed my issue by importing these two modules in your
> `/home/siphon/AttackSurfaceMapper/modules/buckethunter.py` line 43
> 
> ```
>    import colorama
>    from colorama import Fore, Style
> ```
> 
> Hope this helps. Cheers

fixed the issue on my end as well, thank you!

**Comment by Sipho68** [comment]
Thank you for the assistance, importing module worked.
