### ISSUE TITLE
Duplication in "requirements.txt"

### ISSUE THREAD

**Issue by cactaceae21** [superhedgy/AttackSurfaceMapper#24]
`python -m pip install --no-cache-dir -r requirements.txt` gives the error 

> Double requirement given: selenium>=3.141.0 (from -r requirements.txt (line 16)) (already in selenium (from -r requirements.txt (line 11)), name='selenium')

Resolved by removing line 11 or 16

**Comment by superhedgy** [comment]
Thanks for raising this @cactaceae21 ! Fixed. Please download the latest version of the git.
