### ISSUE TITLE
LinkedIN username

### ISSUE THREAD

**Issue by brohan** [superhedgy/AttackSurfaceMapper#27]
The keylists.asm has 2 lines for LinkedIn, the username and password. LinkedIn doesn't have usernames from what I can tell, only your email address. When I give my registered email address and password I still get an error:

"[*] Error: Could not authenticate to LinkedIn. cannot use a string pattern on a bytes-like object"

**Comment by superhedgy** [comment]
Yeah LinkedIn username refers to the email address associated with the linkedin account.

You should use the following format:

```
linkedin_username = "myemail@example.com"
linkedin_password = "p@ssword1"
```

Make sure you have included the double quotes.

**Comment by cheezee0101** [comment]
I have the same issue and the double quotes are included.

**Comment by PolarBearGod** [comment]
Is there a particular reason why we are avoiding using LinkedIn APIs?
https://www.linkedin.com/developers/

**Comment by jamiemardis** [comment]
Same issue here, the keylist.asm file is correct

**Comment by superhedgy** [comment]
@PolarBearGod not quite the same but I will have a look into it as a possible alternative.

**Comment by H4ckW0lf** [comment]
Hi, 

I have the same issue, I put my LinkedIn credentials but doesn't work and I got this error: 

[*] Error: Could not authenticate to LinkedIn. cannot use a string pattern on a bytes-like object

Traceback (most recent call last):
  File "asm.py", line 947, in <module>
    main(keychain, sw1, output_path, c1)
  File "asm.py", line 739, in main
    keychain["linkedin_password"], "", answer2)
  File "/opt/AttackSurfaceMapper/modules/linkedinner.py", line 115, in get_emails_for_company_name
    cookies['JSESSIONID'] = 'ajax:0397788525211216808'
TypeError: 'NoneType' object does not support item assignment

**Comment by superhedgy** [comment]
@H4ckW0lf I have tested the LinkedInner module again and it works fine for me.

It appears that the error message quoted only shows up when authentication with LinkedIn has failed.

- Make sure the LinkedIn user login credentials are valid.

- **Disable 2-FA for the LinkedIn account your are using before launching AttackSurfaceMapper.**

**Comment by H4ckW0lf** [comment]
@superhedgy thanks!!I have tested again but the problem persists even when 2-FA is disabled for the linkedIn account. 

Will I be setting a bad parameter?

I'm using this format : 

linkedin_username = "myemail@example.com"
linkedin_password = "p@ssword1"

**Comment by lujyun** [comment]
@H4ckW0lf I modified the variable parse in linkedinner.py and solved the problem.

parse = BeautifulSoup(page.decode('utf-8'), "html.parser")
