### ISSUE TITLE
Error on intial run

### ISSUE THREAD

**Issue by Pilly170** [superhedgy/AttackSurfaceMapper#30]
Traceback (most recent call last):
  File "asm.py", line 939, in <module>
    keyloader(keychain, sw1)  # Key Loader
  File "asm.py", line 428, in keyloader
    keychain[tmp[0]] = tmp[2].replace("\"", "")
IndexError: list index out of range

Tried with and without wordlist, different domains.
keys look ok, although couldnt add weleakinfo keys as they are no longer around.

**Comment by superhedgy** [comment]
Hi @Pilly170 I don't seem to be able to replicate this error. What is your host OS?

**Comment by superhedgy** [comment]
Okey, I have found the problem, pretty simple actually, remove any new lines, spaces or empty keys from your keyfile. I am pushing an update to catch this error.
