### ISSUE TITLE
weleakinfo.com

### ISSUE THREAD

**Issue by acprichard** [superhedgy/AttackSurfaceMapper#36]
It seems that the weleakinfo.com domain has been seized by the FBI, is there another site where we could get leaked credentials from and should this module be removed since the site no longer is available?

**Comment by superhedgy** [comment]
Hi @acprichard, thank you for raising it, there are plenty of sites that do the same thing. However, taking into account that weleakinfo has been taken down I have decided not to replace it with a similar service.

The weleakinfo has been commented out and it is not longer used by ASM. I should remove it, once I get some free time.
