### ISSUE TITLE
keylist.asm

### ISSUE THREAD

**Issue by haxxbard** [superhedgy/AttackSurfaceMapper#4]
Bro, you better check your `keylist.asm` as it seems that **you forgot to delete all of your creds**.

**Comment by treebuilder** [comment]
Additionally, GreenWolf and raystyle both forked the project prior to the commit to remove keylist.asm, and it's still publicly available in their forks.

**Comment by haxxbard** [comment]
& please don't forget to clean up your history - thx!

**Comment by superhedgy** [comment]
Thanks guys, we removed it. Nothing sensitive in the file, as the accounts were created just for testing.

**Comment by DeepCodeSec** [comment]
keylist.asm template file for customization:

```
virustotal = ""
hunterio = ""
shodan = ""
weleakinfo = ""
weleakinfo_priv = ""
linkedin_username = ""
linkedin_password = ""
grayhatwarfare = ""
```

**Comment by haxxbard** [comment]
Found no more keys in repo nor history
