### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by honeypot2k** [superhedgy/AttackSurfaceMapper#7]
Could you kindly provide the requirements.txt for installing ?

Thank you

**Comment by danzek** [comment]
It appears to be part of the initial commit....

https://github.com/superhedgy/AttackSurfaceMapper/blob/master/requirements.txt

**Comment by necrose99** [comment]
Setup.py would be a plus,  as could be compiled for many system types 

But very trivial for Gentoo  or @pentoo  package as an ebuild.

**Comment by superhedgy** [comment]
@honeypot2k the requirements.txt is in the initial commit. What's the issue you are running into? What OS are you using?
