### ISSUE TITLE
Installation Kali/OSx/Termux

### ISSUE THREAD

**Issue by rascyber** [superhedgy/AttackSurfaceMapper#9]
Hi

I seem to be battling to successfully run the ASM. I have cloned, run installation of the requirements.txt in MacOSx and Kali still getting same error below;
`<pre><font color="#EF2929"><b>root@kali</b></font>:<font color="#729FCF"><b>/home/AttackSurfaceMapper</b></font># python3 ASM.py -t bbc.co.uk -ln -o demo_run -w resources/top100_sublist.txt
Traceback (most recent call last):
  File &quot;ASM.py&quot;, line 39, in &lt;module&gt;
    from modules import urlscanio
  File &quot;/home/AttackSurfaceMapper/modules/urlscanio.py&quot;, line 8, in &lt;module&gt;
    import ASM
  File &quot;/home/AttackSurfaceMapper/ASM.py&quot;, line 41, in &lt;module&gt;
    from modules import screencapture
  File &quot;/home/AttackSurfaceMapper/modules/screencapture.py&quot;, line 22, in &lt;module&gt;
    from selenium import webdriver
ModuleNotFoundError: No module named &apos;selenium&apos;
</pre>
`

See log above. Tried installing all modules separately still no success running ASM.py

**Comment by DFW1N** [comment]
Run these if you are using linux
use sudo apt-get install python3-pip to install pip for python3
use sudo python3 -m pip install -U selenium to install selenium for python3
Hopefully fixes it for you

**Comment by rascyber** [comment]
Sweet now it runs, and throws this exception after adding the target: I guess it has something to do with API key where do I get?

![Screenshot from 2019-08-10 14-35-12](https://user-images.githubusercontent.com/1847515/62821873-37527380-bb7c-11e9-91e6-3b58ced2e171.png)

How to fix

**Comment by superhedgy** [comment]
I've updated the buckethunter.py module, can you pull and try running it again ?

**Comment by redax2882** [comment]
![2019-08-10 10_07_34-kali-1 - VMware Workstation](https://user-images.githubusercontent.com/34322989/62824126-c77dc200-bb56-11e9-801f-1b8e24533c70.jpg)

**Comment by rascyber** [comment]
> I've updated the buckethunter.py module, can you pull and try running it again ?

Let me do exactly that

**Comment by rascyber** [comment]
After pull run the requirements.txt all satisfied

But get this error

![Screenshot from 2019-08-10 18-41-01](https://user-images.githubusercontent.com/1847515/62824462-9fb24c80-bb9e-11e9-82e3-66295b7b2247.png)

**Comment by davecoutts** [comment]
buckethunter.py appears to be missing the colorama imports.
Add the two lines below to the import section of buckethunter.py and it works.

import colorama
from colorama import Fore, Style

**Comment by ZMMXG2109** [comment]
I'm having trouble as well weather I'm just trying to run the program or execute it I'll get an error saying I have no internet. Which is odd given I have access to the internet still.
![Screenshot from 2019-08-11 01-03-33](https://user-images.githubusercontent.com/54000124/62835659-d96f6b80-bc0f-11e9-87be-dc2be7ce56fc.png)

**Comment by ojensen5115** [comment]
@ZMMXG2109 you are targeting a private IP address. I don't know whether that's related to the problem you're seeing, but I'm also not sure what you're hoping to accomplish.

**Comment by ZMMXG2109** [comment]
I'm currently a student and i was hopping to use your program for class as our teacher is having use determine vulnerabilities on our class room network with each student having 11 virtual machines. If this was not what the program was intended for I do apologize for my confusion and if that is the case would you be willing to suggest a program that might help in that endeavor?

________________________________

**Comment by rascyber** [comment]
> import colorama
> from colorama import Fore, Style

I added this lines. now getting now error:
[*] Error: [*] Error: connecting with GrayHatWarfare API

**Comment by ojensen5115** [comment]
@ZMMXG2109 I'm not involved with this project, just looking at the issues and trying to help out as much as I can. Unfortunately your use case is not what this application does. What you're looking for is a vulnerability scanner.

@rascyber if you look at the bottom of your stack trace, you'll see that selenium seems to have crashed. That looks like something you'll need to resolve on your end.

**Comment by rascyber** [comment]
> @ZMMXG2109 I'm not involved with this project, just looking at the issues and trying to help out as much as I can. Unfortunately your use case is not what this application does. What you're looking for is a vulnerability scanner.
> 
> @rascyber if you look at the bottom of your stack trace, you'll see that selenium seems to have crashed. That looks like something you'll need to resolve on your end.

Sure will do. Just to confirm. what version of Chromedriver and Selenium are you using.

**Comment by ojensen5115** [comment]
@rascyber I'm using Selenium 3.141.0, not sure about Chromedriver. If I `pip freeze` within my working environment I get:

```
appdirs==1.4.3
asn1crypto==0.24.0
attrs==19.1.0
beautifulsoup4==4.8.0
bs4==0.0.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
click-plugins==1.1.1
colorama==0.4.1
cryptography==2.7
cssselect==1.1.0
dnslib==0.9.10
dnspython==1.16.0
fake-useragent==0.1.11
idna==2.8
ipwhois==1.1.0
jsonschema==3.0.2
lxml==4.4.0
netaddr==0.7.19
parse==1.12.0
pkg-resources==0.0.0
pycparser==2.19
pyee==6.0.0
pymongo==3.8.0
pyOpenSSL==19.0.0
pyppeteer==0.0.25
pyquery==1.4.0
pyrsistent==0.15.4
requests==2.22.0
requests-html==0.10.0
selenium==3.141.0
shodan==1.14.0
six==1.12.0
soupsieve==1.9.2
tld==0.9.3
tqdm==4.33.0
trans==2.1.0
urllib3==1.25.3
validator-collection==1.3.5
w3lib==1.21.0
websockets==8.0.2
XlsxWriter==1.1.8
```

**Comment by rascyber** [comment]
> @rascyber I'm using Selenium 3.141.0, not sure about Chromedriver. If I `pip freeze` within my working environment I get:
> 
> ```
> appdirs==1.4.3
> asn1crypto==0.24.0
> attrs==19.1.0
> beautifulsoup4==4.8.0
> bs4==0.0.1
> certifi==2019.6.16
> cffi==1.12.3
> chardet==3.0.4
> Click==7.0
> click-plugins==1.1.1
> colorama==0.4.1
> cryptography==2.7
> cssselect==1.1.0
> dnslib==0.9.10
> dnspython==1.16.0
> fake-useragent==0.1.11
> idna==2.8
> ipwhois==1.1.0
> jsonschema==3.0.2
> lxml==4.4.0
> netaddr==0.7.19
> parse==1.12.0
> pkg-resources==0.0.0
> pycparser==2.19
> pyee==6.0.0
> pymongo==3.8.0
> pyOpenSSL==19.0.0
> pyppeteer==0.0.25
> pyquery==1.4.0
> pyrsistent==0.15.4
> requests==2.22.0
> requests-html==0.10.0
> selenium==3.141.0
> shodan==1.14.0
> six==1.12.0
> soupsieve==1.9.2
> tld==0.9.3
> tqdm==4.33.0
> trans==2.1.0
> urllib3==1.25.3
> validator-collection==1.3.5
> w3lib==1.21.0
> websockets==8.0.2
> XlsxWriter==1.1.8
> ```
> 
> In case it is also helpful:
> 
> ```
> $ google-chrome --version
> Google Chrome 76.0.3809.100
> ```
> 
> though to be clear, I'm running on Debian and not Kali

two days tried to fix this chrome crash issue. No luck.
elenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.0-kali5-amd64 x86_64)

Any solution quick fix will be appreciated.

**Comment by ojensen5115** [comment]
@rascyber based on a Google search for "DevToolsActivePort file doesn't exist" it looks like there can be a number of potential causes for this issue. Which approaches have you tried so far that didn't work for you?
